import './globals.css'
import '../public/fonts.css'
import type { Metadata } from 'next'
import Header from '@/components/ui/header'
import Footer from '@/components/ui/footer'
import { OrderProvider } from '@/context/OrderContext'

import  { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Tarkhineh | restaurant',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <OrderProvider>
        <Header/>
        <main className='md:container mx-1'>
        {children}
        </main>
        <Footer />
        <Toaster position='bottom-left' />
        </OrderProvider>
      </body>
    </html>
  )
}
